language: cpp
sudo: true
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-image1.2-dev
    - byacc
    - gtk+-2.0-dev
    - gcc-5
    - g++-5

compiler:
    - g++

services:
    - docker

#Build steps
before_install:
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++

jobs:
  include:
    - stage: build
      name: "direct build"
      script:
        - ./autogen.sh
        - CFLAGS="$CFLAGS -w -fuse-ld=gold" CXXFLAGS="$CXXFLAGS -fpermissive -w -fuse-ld=gold" ./configure --enable-silent-rules
        - make
    - stage: build
      name: "direct debug build"
      script:
        - ./autogen.sh
        - CFLAGS="$CFLAGS -w -fuse-ld=gold" CXXFLAGS="$CXXFLAGS -fpermissive -w -fuse-ld=gold" ./configure --enable-silent-rules --enable-debug
        - make
    - stage: build
      name: "docker build"
      script:
        - docker build --pull .
